### ISSUE TITLE
misleading readme

### ISSUE THREAD

**Issue by Sharp-Eyes** [EnokiUN/EnokiUN#2]
Um, ackshually... you're not a high school student anymore!!

**Comment by ashleney** [comment]
![image](https://github.com/user-attachments/assets/1aed9fe7-ca6b-417e-8851-ed61c9962b4c)
I have not seen you use half of these in ages!!!

**Comment by EnokiUN** [comment]
> ![image](https://private-user-images.githubusercontent.com/58166507/368568771-1aed9fe7-ca6b-417e-8851-ed61c9962b4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NjMzMTQsIm5iZiI6MTcyNjY2MzAxNCwicGF0aCI6Ii81ODE2NjUwNy8zNjg1Njg3NzEtMWFlZDlmZTctY2E2Yi00MTdlLTg4NTEtZWQ2MWM5OTYyYjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDEyMzY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNzU5MGQzM2Y1OWYzMDdkODAwZjcyNjhhNzhiZTNlNGFhYTQxODA1NjdiZTQyNWIxZjc1ZDAyNTcyNDJkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O9yi-N6P7uUFIWHcElXGlyK38JjEC5t8QGVI7SN1aok) I have not seen you use half of these in ages!!!

how do you know? :raised_eyebrow:

**Comment by Sharp-Eyes** [comment]
ashlen was there when you didn't use them

**Comment by EnokiUN** [comment]
> ashlen was there when you didn't use them

so was your dullahan

**Comment by Sharp-Eyes** [comment]
wow thanks for fixing my issue :heart:
